image: python:3.11

definitions:
  steps:
    - step: &lint-code
        name: Lint Code with Flake8
        script:
          - pip install flake8
          - flake8 . --extend-exclude=dist,build --show-source --statistics --max-line-length 80

    - step: &type-check
        name: Type Check with MyPy
        script:
          - pip install mypy
          - mypy .

pipelines:
  pull-requests:
    '**':
      - step: *lint-code
      - step: *type-check

  branches:
    main:
      - step: *lint-code
      - step: *type-check
    development:
      - step: *lint-code
      - step: *type-check
