#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.11

definitions:
  steps:
    - step: &lint-code
        name: Lint Code with Flake8
        script:
          - pip install flake8
          - flake8 . --extend-exclude=dist,build --show-source --statistics --max-line-length 80

    - step: &type-check
        name: Type Check with MyPy
        script:
          - pip install mypy
          - mypy .

pipelines:
  branches:
    main:
      - <<: *lint-code
      - <<: *type-check
    development:
      - <<: *lint-code
      - <<: *type-check
