#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.11

pipelines:
  default:
    - parallel:
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics --max-line-length 80            
      - step:
          name: MyPy Type Checking
          script:
            - pip install mypy
            - mypy .
