image: python:3.11

definitions:
  steps:
    -parallel:
      - step: &lint-code
          fail-fast: false
          name: Lint Code with Flake8
          script:
            - pip install ruff
            - ruff check .

      - step: &type-check
          name: Type Check with MyPy
          script:
            - pip install mypy
            - pip install types-requests
            - mypy .

pipelines:
  pull-requests:
    '**':
      - step: *lint-code
      - step: *type-check

  branches:
    main:
      - step: *lint-code
      - step: *type-check
    development:
      - step: *lint-code
      - step: *type-check
